"""empty message

Revision ID: 3ebe80acac41
Revises: None
Create Date: 2014-11-25 02:07:32.715063

"""

# revision identifiers, used by Alembic.
revision = '3ebe80acac41'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Path', sa.Column('IP', sa.String(length=255)))
    op.add_column('Path', sa.Column('Method', sa.String(length=255)))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Path', 'Method')
    op.drop_column('Path', 'IP')
    ### end Alembic commands ###
