"""empty message

Revision ID: 4d436073019d
Revises: None
Create Date: 2014-11-19 11:17:09.030561

"""

# revision identifiers, used by Alembic.
revision = '4d436073019d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
