"""empty message

Revision ID: 53fdccaa7156
Revises: 710d5081fa7
Create Date: 2014-11-25 22:49:42.644978

"""

# revision identifiers, used by Alembic.
revision = '53fdccaa7156'
down_revision = '710d5081fa7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Config',
    sa.Column('Key', sa.String(length=255), nullable=False),
    sa.Column('Value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Config')
    ### end Alembic commands ###
